[build]
  command = "npm run build"
  publish = "build"           
  # publish = "dist"           

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
    output_path = "lighthouse"   
